spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1030
    url: jdbc:mysql://localhost:3306/emplorium
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
  mail:
    host: smtp.gmail.com
    port: 587
    username: nodemailercharan@gmail.com
    password: brftpryzsogquwjk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
